[build]
  publish = "public"
  command = "pip install --upgrade pip && pip install -r requirements.txt && gunicorn main:app --bind 0.0.0.0:$PORT"

[[redirects]]
  from = "/*"
  to = "/.netlify/functions/server"
  status = 200